### ISSUE TITLE
Add healthcheck endpoint

### ISSUE THREAD

**Issue by phenixblue** [phenixblue/imageswap-webhook#12]
Need to add a health check endpoint to be used for liveness/readiness probes. 

I think `/healthz` with a simple `200 OK` should be sufficient.

**Comment by anushri20** [comment]
Hi, Can I work on this?

**Comment by phenixblue** [comment]
Sure @anushri20

**Comment by phenixblue** [comment]
Hi @anushri20 I had most of this queued up already, so I just went ahead and pushed the update. Sorry for the confusion.

Implemented as part of #13
