### ISSUE TITLE
ECR Style Repo Support

### ISSUE THREAD

**Issue by wtistio** [phenixblue/imageswap-webhook#14]
Hello,

Firstly thank you to the maintainers and contributors to this excellent project. I was hoping something like this existed and it's really exactly what I am after.

I am building a network isolated EKS Kubernetes cluster and want to mirror public docker images to my ECR repository.

I set `IMAGE_PREFIX` to the ECR repo `111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-`

But when I run a test container, in this case based off the  `debian` image, instead of `mirror-debian` being the new image, it is this:

```
[2020-10-20 13:43:31,809] INFO in imageswap: External image definition detected: debian
[2020-10-20 13:43:31,809] INFO in imageswap: External image updated to Internal image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-/debian
```

I was hoping it would be replaced with `111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-debian`.

It does look pretty wacky, but ECR repository names can include slashes, etc, so I am going to mirror public image paths exactly as they appear in the YAML. Eg, for non-docker hub URLs:

```
111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-quay.io/calico/node
111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-k8s.gcr.io/cluster-proportional-autoscaler-amd64
```

I hope the report makes sense and you can help.

Thanks in advance

**Comment by phenixblue** [comment]
OK, does this look like the desired input/output images you're looking for?

Assuming `IMAGE_PREFIX=111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-`

```
External image definition detected: debian:latest
External image updated to Internal image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-debian:latest
```

```
External image definition detected: quay.io/calico/node:latest
External image updated to Internal image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/mirror-quay.io/calico/node:latest
```

**Comment by wtistio** [comment]
Thanks for responding, @phenixblue, I can confirm that's the desired output 👍

**Comment by phenixblue** [comment]
Ok, I think I have that logic worked out, I just need to test it a bit more. Should have a new release that includes this within the next couple of days.

**Comment by wtistio** [comment]
Wow, thank you very much, I appreciate you taking the time to look at my feature request. Thanks again!

**Comment by phenixblue** [comment]
Ok @wtistio . Please check out the v1.3.0 release and let me know how that works for you.

**Comment by wtistio** [comment]
Thanks @phenixblue I've just tested 1.3.0 and can confirm it's working as expected. Thank you again for your help and this great project 👍 😄
