### ISSUE TITLE
default imageswap-sa serviceaccount does not has permission to read extension-apiserver-authentication configmap in kube-system namespace

### ISSUE THREAD

**Issue by rainsun** [phenixblue/imageswap-webhook#56]
**What happened**:
after run kubectl apply -f install.yaml, the init container can not get the correct ca cert
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f deploy/install.yaml
kubectl auth can-i get cm --as=system:serviceaccount:imageswap-system:imageswap-sa -n kube-system
no
**Anything else we need to know?**:

**Environment**:
bare k3s
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- Others:

**Comment by phenixblue** [comment]
Can you please collect the init-container logs from one of the imageswap pods in your environment with DEBUG logging enabled:

- Edit the `imageswap-env` configMap and set `IMAGESWAP_LOG_LEVEL: DEBUG`
- Force the pods to recycle (delete, rollout restart, etc.)
- Collect the logs:

```
$ kubectl logs -n imageswap-system <pod_name> -c imageswap-init
```

I think this may be related to an issue with the certificates.k8s.io/v1beta1 API and the newer version of k8s in your environment. We currently test against k8s v1.17 - v1.20. I should know more once I can see the debug log output.
