### ISSUE TITLE
Nice work ;-)

### ISSUE THREAD

**Issue by micw** [phenixblue/imageswap-webhook#7]
Hello,
I stumbled across this when looking for a python example of a webhook to learn how it works. Found here exactly what I was looking for.
Just one suggestion: The creation of the required cert secret can easily be done by another job/container. The people from cert-manager created one that injects such a cert by annotations:

https://github.com/jetstack/cert-manager/tree/master/cmd/cainjector
https://docs.cert-manager.io/en/latest/reference/cainjector.html

Best regards,
Michael.

**Comment by phenixblue** [comment]
Thanks! This repo is certainly a bit dated at this point. I have a project I hope to open source soon that will serve as a better example and will likely use CertManager to handle the certificates. Keep an eye out.
