### ISSUE TITLE
New release including PR-85

### ISSUE THREAD

**Issue by m-barthelemy** [phenixblue/imageswap-webhook#94]
Hi,

**What would you like to be added**:
We're interested in trying the `replace_maps` option introduced in https://github.com/phenixblue/imageswap-webhook/pull/85
However it looks like there hasn't been a new release of Imageswap and associated Docker Hub image.

Would it be possible to create a new release + Docker image with the changes merged since last August?

**Why is this needed**:

Always nice to be able to rely on an existing/already built Docker images matching release tags!

**Comment by phenixblue** [comment]
Hi @m-barthelemy , I have been swamped for the past several months, but I will try to get this done soon

**Comment by phenixblue** [comment]
Hey @m-barthelemy I now have #96 open to prep for the release of v1.5.2 that includes #85. Waiting on a PR review, but should hopefully have the release cut in a few days

**Comment by m-barthelemy** [comment]
Thanks a lot @phenixblue !
